In [7]:
import pandas as pd
import numpy as np

In [8]:
# object creation
S = pd.Series([1,2,3,4,5])
S

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [18]:
dates = pd.date_range ("20220101", periods =10)
dates

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08',
               '2022-01-09', '2022-01-10'],
              dtype='datetime64[ns]', freq='D')

In [31]:
df =pd.DataFrame(np.random.randn(10,4), columns=list("LALU"))
df

          L         A         L         U
0 -0.392622  0.843422  0.101202 -1.061907
1 -0.404271  0.599379 -0.131306  0.081315
2 -0.980483  1.750748 -2.344604  0.570129
3 -0.264422  0.753402  1.986988 -0.927564
4  0.552012 -1.661716 -0.043985 -1.701020
5  1.342485 -0.719345 -1.631878 -2.185780
6  0.305403 -0.161625  0.895818  0.267837
7 -1.416656 -0.432468 -0.826268 -1.148109
8  1.752380  1.826531  0.874805  0.982452
9 -0.348348  0.610045  0.725340  0.318048

In [16]:
df2 = pd.DataFrame (
    {
    "A":1.0,
    "B":pd.Timestamp("20130102"),
    "C":pd.Series(1, index=list(range(4)), dtype="float32"),
    "D":pd.Categorical (["girl", "train", "test", "train"]),
    "F":"Females",
}
)
df2

     A          B    C      D        F
0  1.0 2013-01-02  1.0   girl  Females
1  1.0 2013-01-02  1.0  train  Females
2  1.0 2013-01-02  1.0   test  Females
3  1.0 2013-01-02  1.0  train  Females

In [25]:

df5 = pd.DataFrame ( 
    {
    "A":1.0,
    "B":pd.Timestamp("20130102"),
    "C":pd.Series(1, index=list(range(4)), dtype="float32"),
    "D":pd.Categorical (["girl", "women", "test", "truck"]),
    "F":"Females",
}
)   

print(df5)

     A          B    C      D        F
0  1.0 2013-01-02  1.0   girl  Females
1  1.0 2013-01-02  1.0  women  Females
2  1.0 2013-01-02  1.0   test  Females
3  1.0 2013-01-02  1.0  truck  Females

In [28]:
mport pandas as pd
Load = pd.read_csv ("FAOSTAT_data_1-12-2022.csv")
Loadi

,Domain Code,Domain,Area Code,Area,Element Code,Element,Item Code,Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note
0,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20002002,2000-2002,millions,30.8,F,FAO estimate,NaN
1,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20012003,2001-2003,millions,32.5,F,FAO estimate,NaN
2,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20022004,2002-2004,millions,32.1,F,FAO estimate,NaN
3,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20032005,2003-2005,millions,29.8,F,FAO estimate,NaN
4,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20042006,2004-2006,millions,28.2,F,FAO estimate,NaN
5,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20052007,2005-2007,millions,26.8,F,FAO estimate,NaN
6,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20062008,2006-2008,millions,26.5,F,FAO estimate,NaN
7,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20072009,2007-2009,millions,27.1,F,FAO estimate,NaN
8,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20082010,2008-2010,millions,28.0,F,FAO estimate,NaN
9,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20092011,2009-2011,millions,28.6,F,FAO estimate,NaN
10,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20102012,2010-2012,millions,29.2,F,FAO estimate,NaN
11,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20112013,2011-2013,millions,29.7,F,FAO estimate,NaN
12,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20122014,2012-2014,millions,28.9,F,FAO estimate,NaN
13,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20132015,2013-2015,millions,27.1,F,FAO estimate,NaN
14,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20142016,2014-2016,millions,25.5,F,FAO estimate,NaN
15,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20152017,2015-2017,millions,25.2,F,FAO estimate,NaN
16,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20162018,2016-2018,millions,25.2,F,FAO estimate,NaN
17,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20172019,2017-2019,millions,25.8,F,FAO estimate,NaN
18,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20182020,2018-2020,millions,27.9,F,FAO estimate,NaN

In [31]:
Load.tail(2)

,Domain Code,Domain,Area Code,Area,Element Code,Element,Item Code,Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note
17,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20172019,2017-2019,millions,25.8,F,FAO estimate,NaN
18,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20182020,2018-2020,millions,27.9,F,FAO estimate,NaN

In [35]:
import pandas as pd
Load = pd.read_csv ("FAOSTAT_data_1-12-2022.csv",header=None)
Load

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,Domain Code,Domain,Area Code,Area,Element Code,Element,Item Code,Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note
1,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20002002,2000-2002,millions,30.8,F,FAO estimate,NaN
2,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20012003,2001-2003,millions,32.5,F,FAO estimate,NaN
3,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20022004,2002-2004,millions,32.1,F,FAO estimate,NaN
4,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20032005,2003-2005,millions,29.8,F,FAO estimate,NaN
5,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20042006,2004-2006,millions,28.2,F,FAO estimate,NaN
6,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20052007,2005-2007,millions,26.8,F,FAO estimate,NaN
7,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20062008,2006-2008,millions,26.5,F,FAO estimate,NaN
8,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20072009,2007-2009,millions,27.1,F,FAO estimate,NaN
9,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20082010,2008-2010,millions,28,F,FAO estimate,NaN
10,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20092011,2009-2011,millions,28.6,F,FAO estimate,NaN
11,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20102012,2010-2012,millions,29.2,F,FAO estimate,NaN
12,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20112013,2011-2013,millions,29.7,F,FAO estimate,NaN
13,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20122014,2012-2014,millions,28.9,F,FAO estimate,NaN
14,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20132015,2013-2015,millions,27.1,F,FAO estimate,NaN
15,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20142016,2014-2016,millions,25.5,F,FAO estimate,NaN
16,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20152017,2015-2017,millions,25.2,F,FAO estimate,NaN
17,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20162018,2016-2018,millions,25.2,F,FAO estimate,NaN
18,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20172019,2017-2019,millions,25.8,F,FAO estimate,NaN
19,FS,Suite of Food Security Indicators,165,Pakistan,6132,Value,210011,Number of people undernourished (million) (3-y...,20182020,2018-2020,millions,27.9,F,FAO estimate,NaN